[versions]
kotlin = "2.1.0"
coroutines = "1.10.1"
ktor = "2.3.13"
kimchi = "2.2.0"
watermelon = "1.8.1"
regolith = "1.6.0"
glass = "0.16.0"
sqldelight = "1.5.5"

##
# Kotlin Libraries
##

[libraries.kotlin-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"

[libraries.kotlin-test-core]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test"

[libraries.kotlin-test-junit]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test-junit"

[libraries.kotlin-coroutines-core]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"

[libraries.kotlin-coroutines-test]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"

[libraries.kotlin-coroutines-js]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js"

[libraries.kotlin-datetime]
version = "0.6.0"
module = "org.jetbrains.kotlinx:kotlinx-datetime"

[libraries.kotlin-serialization-json]
version = "1.7.3"
module = "org.jetbrains.kotlinx:kotlinx-serialization-json"

[libraries.kotlin-serialization-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-serialization"

##
# Ktor Libraries
##

[libraries.ktor-client-core]
version.ref = "ktor"
module="io.ktor:ktor-client-core"

[libraries.ktor-serialization-json]
version.ref = "ktor"
module = "io.ktor:ktor-serialization-kotlinx-json"

[libraries.ktor-client-serialization]
version.ref = "ktor"
module="io.ktor:ktor-client-serialization"

[libraries.ktor-client-okhttp]
version.ref = "ktor"
module="io.ktor:ktor-client-okhttp"

[libraries.ktor-client-cio]
version.ref = "ktor"
module="io.ktor:ktor-client-cio"

[libraries.ktor-client-js-core]
version.ref = "ktor"
module="io.ktor:ktor-client-js"

[libraries.ktor-client-js-json]
version.ref = "ktor"
module="io.ktor:ktor-client-json-js"

[libraries.ktor-server-netty]
version.ref = "ktor"
module="io.ktor:ktor-server-netty"

[libraries.ktor-server-websockets]
version.ref = "ktor"
module="io.ktor:ktor-server-websockets"

[libraries.ktor-client-websockets]
version.ref = "ktor"
module="io.ktor:ktor-client-websockets"

[libraries.ktor-client-contentnegotiation]
version.ref = "ktor"
module="io.ktor:ktor-client-content-negotiation"

##
# Ink Libraries
##

[libraries.kimchi-core]
version.ref = "kimchi"
module = "com.inkapplications.kimchi:core"

[libraries.kimchi-logger]
version.ref = "kimchi"
module = "com.inkapplications.kimchi:logger"

[libraries.spondee]
version = "1.3.0"
module = "com.inkapplications.spondee:units"

[libraries.watermelon-coroutines]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:coroutines"

[libraries.watermelon-standard]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:standard"

[libraries.watermelon-datetime]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:datetime"

[libraries.regolith-processes]
version.ref = "regolith"
module = "com.inkapplications.regolith:processes"

[libraries.regolith-timemachine]
version.ref = "regolith"
module = "com.inkapplications.regolith:time-machine"

[libraries.regolith-data]
version.ref = "regolith"
module = "com.inkapplications.regolith:data"

[libraries.glass-client]
version.ref = "glass"
module = "com.inkapplications.glassconsole:client"

[libraries.glass-structures]
version = "0.17.0"
module = "com.inkapplications.glassconsole:structures"

##
# Other
##

[libraries.sqldelight-gradle]
version.ref = "sqldelight"
module = "com.squareup.sqldelight:gradle-plugin"

[libraries.sqldelight-driver]
version.ref = "sqldelight"
module = "com.squareup.sqldelight:sqlite-driver"

[libraries.sqldelight-coroutines]
version.ref = "sqldelight"
module = "com.squareup.sqldelight:coroutines-extensions"

[libraries.iospin-libsodium]
version = "0.9.2"
module = "com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings"

[libraries.junit]
version = "4.12"
module = "junit:junit"

[libraries.sunrisesunsetcalculator]
version = "1.2"
module = "com.luckycatlabs:SunriseSunsetCalculator"

[bundles]
watermelon-kotlin = [
    "watermelon-coroutines",
    "watermelon-standard",
    "watermelon-datetime",
]
sqldelight = ["sqldelight-driver", "sqldelight-coroutines"]
